import * as vscode from 'vscode';
// eslint-disable-next-line max-len
import {CompletionItem, TextDocument, Position, CancellationToken, ExtensionContext, Range, CompletionItemKind} from 'vscode';

/**
 * JSDoc Autocompletion item.
 *
 * @extends {CompletionItem}
 * @typedef {GenerateJsdocCompletionItem}
 */
class GenerateJsdocCompletionItem extends CompletionItem {
  /**
   * @constructor
   * @param {string} line
   * @param {Position} position
   */
  constructor(line: string, position: Position) {
    super('/** Autogenerated JSDoc */', CompletionItemKind.Snippet);

    this.insertText = '';
    this.sortText = '\0';
    this.range = this.retrieveRange(line, position);
    this.command = {
      title: 'Generate JSDoc',
      command: 'jsdoc-generator.generateJsdoc'
    };
  }

  /**
   * Retrieves the range of the JSDoc comment from the current line and the {@link Position} parameter.
   *
   * @private
   * @param {string} line
   * @param {Position} position
   * @returns {Range}
   */
  private retrieveRange(line: string, position: Position): Range {
    const prefix = line.slice(0, position.character).match(/\/\**\s*$/);
    const suffix = line.slice(position.character).match(/^\s*\**\//);
    const start = position.translate(0, prefix ? -prefix[0].length : 0);
    return new Range(start, position.translate(0, suffix ? suffix[0].length : 0));
  }
}

/**
 * Called when the extension is activated, subscribes the autocompletion item and the commands in the context.
 *
 * @export
 * @param {ExtensionContext} context
 */
export function activate(context: ExtensionContext) {
  // eslint-disable-next-line no-console
  console.log('Extension "jsdoc-generator" is now active!');
  // Generates JSDoc with auto completion.
  const generateJsdocAutocompletion = vscode.languages.registerCompletionItemProvider(
    [
      {
        scheme: 'file',
        language: 'javascript'
      }, {
        scheme: 'file',
        language: 'typescript'
      }
    ],
    {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      provideCompletionItems(document: TextDocument, position: Position, token: CancellationToken) {
        const line = document.lineAt(position.line).text;
        const prefix = line.slice(0, position.character);
        if(prefix.match(/^\s*\/\*\*\s*$/)) {
          return [new GenerateJsdocCompletionItem(line, position)];
        }
        return null;
      }
    },
    '/',
    '*'
  );
  // Generates JSDoc for the current selection.
  const generateJsdoc = vscode.commands.registerCommand('jsdoc-generator.generateJsdoc', () => {
    // TODO: implement
    vscode.window.showInformationMessage('JSDoc generated!');
  });
  // Generates JSDoc for every suitable element in the current file.
  const generateJsdocFile = vscode.commands.registerCommand('jsdoc-generator.generateJsdocFile', () => {
    // TODO: implement
    vscode.window.showInformationMessage('Generating JSDoc for this file...');
  });
  // Generates JSDoc for every suitable element in every ts or js file.
  const generateJsdocFiles = vscode.commands.registerCommand('jsdoc-generator.generateJsdocFiles', () => {
    // TODO: implement
    vscode.window.showInformationMessage('Generating JSDoc for every file...');
  });
  context.subscriptions.push(generateJsdoc, generateJsdocFile, generateJsdocFiles, generateJsdocAutocompletion);
}

/**
 * This method is called when the extension is deactivated
 *
 * @export
 */
export function deactivate() {
  // Empty on purpose
}
